#!/bin/bash
#
# ryu 
#
# chkconfig:   - 23 88
# description: Ryu is OpenFlow Controller
# processname: ryu
# config:      /etc/ryu/ryu.conf
#
### BEGIN INIT INFO
# Provides: ryu
# Required-Start: $local_fs 
# Required-Stop: $local_fs 
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: start and stop ryu
# Description: Ryu is OpenFlow Controller
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

exec="/opt/qcrypt/sbin/ryu"
prog=ryu-manager
lockfile=/var/lock/subsys/$prog

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start() {
 	echo -n $"Starting $prog"
	daemon $exec
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $lockfile
	return $retval
}

stop() {
	echo -n $"Stopping $prog: "
	killproc $prog
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $lockfile
	return $retval
}

restart() {
	stop
	start
}

reload() {
	restart
}

force_reload() {
	restart
}

fdr_status() {
	status $prog
}


case "$1" in
	start|stop|restart|reload)
  		$1
		;;
	force-reload)
		force_reload
		;;
	status)
		fdr_status
		;;
	condrestart|try-restart)
		[ -f $lockfile ] && restart
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
		exit 1
esac

