#!/bin/sh


# N1 eth1
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":2, "dl_dst":"00:50:fc:64:5c:6e"}, "actions":[{"type":"OUTPUT", "port":1}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":3, "dl_dst":"00:50:fc:64:5c:6e"}, "actions":[{"type":"OUTPUT", "port":1}]}'
# S1 local
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":1, "dl_dst":"00:00:00:00:00:03"}, "actions":[{"type":"OUTPUT", "port":3}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":2, "dl_dst":"00:00:00:00:00:03"}, "actions":[{"type":"OUTPUT", "port":3}]}'
# S2 macvtap0
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":2, "dl_dst":"52:54:00:9a:1d:34"}, "actions":[{"type":"OUTPUT", "port":1}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":3, "dl_dst":"52:54:00:9a:1d:34"}, "actions":[{"type":"OUTPUT", "port":1}]}'
# S2 macvtap1
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":2, "dl_dst":"52:54:00:d2:cb:9f"}, "actions":[{"type":"OUTPUT", "port":1}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":3, "dl_dst":"52:54:00:d2:cb:9f"}, "actions":[{"type":"OUTPUT", "port":1}]}'
# N2 eth1
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":1, "dl_dst":"00:08:a1:a5:89:f8"}, "actions":[{"type":"OUTPUT", "port":2}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":3, "priority":1, "match":{"in_port":3, "dl_dst":"00:08:a1:a5:89:f8"}, "actions":[{"type":"OUTPUT", "port":2}]}'

# N1 eth1
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":2, "dl_dst":"00:50:fc:64:5c:6e"}, "actions":[{"type":"OUTPUT", "port":1}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":3, "dl_dst":"00:50:fc:64:5c:6e"}, "actions":[{"type":"OUTPUT", "port":1}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":4, "dl_dst":"00:50:fc:64:5c:6e"}, "actions":[{"type":"OUTPUT", "port":1}]}'
# S1 local
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":1, "dl_dst":"00:00:00:00:00:03"}, "actions":[{"type":"OUTPUT", "port":2}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":3, "dl_dst":"00:00:00:00:00:03"}, "actions":[{"type":"OUTPUT", "port":2}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":4, "dl_dst":"00:00:00:00:00:03"}, "actions":[{"type":"OUTPUT", "port":2}]}'
# S2 macvtap0
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":1, "dl_dst":"52:54:00:9a:1d:34"}, "actions":[{"type":"OUTPUT", "port":3}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":2, "dl_dst":"52:54:00:9a:1d:34"}, "actions":[{"type":"OUTPUT", "port":3}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":4, "dl_dst":"52:54:00:9a:1d:34"}, "actions":[{"type":"OUTPUT", "port":3}]}'
# S2 macvtap1
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":1, "dl_dst":"52:54:00:d2:cb:9f"}, "actions":[{"type":"OUTPUT", "port":4}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":2, "dl_dst":"52:54:00:d2:cb:9f"}, "actions":[{"type":"OUTPUT", "port":4}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":3, "dl_dst":"52:54:00:d2:cb:9f"}, "actions":[{"type":"OUTPUT", "port":4}]}'
# N2 eth1
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":1, "dl_dst":"00:08:a1:a5:89:f8"}, "actions":[{"type":"OUTPUT", "port":2}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":3, "dl_dst":"00:08:a1:a5:89:f8"}, "actions":[{"type":"OUTPUT", "port":2}]}'
curl -X POST http://0.0.0.0:8080/stats/flowentry/add -d '{"dpid":4, "priority":1, "match":{"in_port":4, "dl_dst":"00:08:a1:a5:89:f8"}, "actions":[{"type":"OUTPUT", "port":2}]}'

